In [1]:
import pandas as pd

import numpy as np

import scipy.stats as s 

import os

In [2]:
train_data = pd.read_csv("train.csv")

In [3]:
data1=pd.read_csv("test.csv")

In [4]:
data2=pd.read_csv("sample_submission.csv")

In [5]:
test_data=pd.merge(left=data1,right=data2)

In [6]:
test_data

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0           2     2     32                 0.0                      0.0   
1           5     2     35                 0.0                      0.0   
2           6     2     23                 0.0                      0.0   
3           7     2     24                 0.0                      0.0   
4           9     2     23                 0.0                      0.0   
...       ...   ...    ...                 ...                      ...   
75813  151831     2     23                 0.0                      0.0   
75814  151832     2     26                 0.0                      0.0   
75815  151833     2     24                 0.0                      0.0   
75816  151834     2     40                 0.0                      0.0   
75817  151837     2     23                 0.0                      0.0   

       imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  \
0                          0.0                      0.0   
1                          0.0                      0.0   
2                          0.0                      0.0   
3                          0.0                      0.0   
4                          0.0                      0.0   
...                        ...                      ...   
75813                      0.0                      0.0   
75814                      0.0                      0.0   
75815                      0.0                      0.0   
75816                      0.0                      0.0   
75817                      0.0                      0.0   

       imp_op_var40_comer_ult3  imp_op_var40_efect_ult1  \
0                          0.0                      0.0   
1                          0.0                      0.0   
2                          0.0                      0.0   
3                          0.0                      0.0   
4                          0.0                      0.0   
...                        ...                      ...   
75813                      0.0                      0.0   
75814                      0.0                      0.0   
75815                      0.0                      0.0   
75816                      0.0                      0.0   
75817                      0.0                      0.0   

       imp_op_var40_efect_ult3  ...  saldo_medio_var33_hace2  \
0                          0.0  ...                      0.0   
1                          0.0  ...                      0.0   
2                          0.0  ...                      0.0   
3                          0.0  ...                      0.0   
4                          0.0  ...                      0.0   
...                        ...  ...                      ...   
75813                      0.0  ...                      0.0   
75814                      0.0  ...                      0.0   
75815                      0.0  ...                      0.0   
75816                      0.0  ...                      0.0   
75817                      0.0  ...                      0.0   

       saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                          0.0                     0.0   
1                          0.0                     0.0   
2                          0.0                     0.0   
3                          0.0                     0.0   
4                          0.0                     0.0   
...                        ...                     ...   
75813                      0.0                     0.0   
75814                      0.0                     0.0   
75815                      0.0                     0.0   
75816                      0.0                     0.0   
75817                      0.0                     0.0   

       saldo_medio_var33_ult3  saldo_medio_var44_hace2  \
0                         0.0                      0.0   
1                         0.0                      0.0   
2                         0.0                      0

In [7]:
data=pd.concat([train_data,test_data])
x= np.array(data.iloc[:,0:369])

In [8]:
from sklearn.naive_bayes import GaussianNB
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score

In [9]:
target=np.array(train_data.iloc[:,370])

In [10]:
target

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
cv_actual_results=np.array(test_data['TARGET'])

In [12]:
def cross_validation(n_eig_vectors):
    pca_obj = PCA(n_components=n_eig_vectors)
    x_new = pca_obj.fit_transform(x)
    x_train_new = x_new[0:76020,:]
    x_cv_new = x_new[76020:,:]
    obj = GaussianNB()
    obj.fit(x_train_new,target)
    cv_predicted_category = obj.predict(x_cv_new)
    return accuracy_score(y_true=cv_actual_results,y_pred=cv_predicted_category)

In [13]:
eig_vectors = [369,185,90,57,20,10,5,2,1]
d_perform = {}
for number in eig_vectors:
    d_perform[number] = cross_validation(number)

In [14]:
d_perform

{369: 0.033184731857870166,
 185: 0.033184731857870166,
 90: 0.033184731857870166,
 57: 0.033184731857870166,
 20: 0.03273628953546651,
 10: 0.007201456118599805,
 5: 1.0,
 2: 1.0,
 1: 1.0}

# ***

In [15]:
target=data.TARGET

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(data,target,test_size=0.3)

In [17]:
from sklearn.naive_bayes import GaussianNB
obj = GaussianNB()

In [18]:
obj.fit(X_train,Y_train)

GaussianNB()

In [19]:
obj.score(X_test,Y_test)

0.04280821917808219

In [20]:
Y_test

23327    0
38897    0
25880    0
23274    0
71585    0
        ..
9195     0
9232     0
66923    1
70302    0
27913    0
Name: TARGET, Length: 45552, dtype: int64

In [21]:
obj.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [22]:
obj.predict_proba(X_test)

array([[1.66473260e-68, 1.00000000e+00],
       [1.64586898e-68, 1.00000000e+00],
       [1.64856897e-68, 1.00000000e+00],
       ...,
       [1.65377800e-68, 1.00000000e+00],
       [1.60909429e-68, 1.00000000e+00],
       [1.80748861e-68, 1.00000000e+00]])